package com.project.dev.monolith.entity;

import com.project.dev.monolith.enums.MessageRole;
import lombok.AccessLevel;
import lombok.Getter;
import lombok.Setter;
import lombok.experimental.FieldDefaults;

import java.time.Instant;

@FieldDefaults(level = AccessLevel.PRIVATE)
@Getter
@Setter
public class ChatMessage {

    Long id;
    ChatSession chatSession;

    String content; //the actual msg

    String toolCalls; // if any tool is called ,that is stored in a json array

    Integer tokenUsed;

    Instant createdAt;

    MessageRole messageRole; //this shows the message is sent by whom - user or generated by s/m or llm


}
